
kMachineOpMacroFeGetExceptionsTranslateMemBaseDispReg,
    kMachineOpMacroFeSetExceptionsAndRoundImmTranslateMemBaseDispImm,
    kMachineOpMacroFeSetExceptionsAndRoundTranslateRegMemBaseDispRegReg,
    kMachineOpMacroFeSetExceptionsImmTranslateMemBaseDispImm,
    kMachineOpMacroFeSetExceptionsTranslateRegMemBaseDispReg,
    kMachineOpMacroFeSetRoundImmTranslateMemBaseDispMemBaseDispImm,
