/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef BERBERIS_GUEST_ABI_FUNCTION_WRAPPERS_H_
#define BERBERIS_GUEST_ABI_FUNCTION_WRAPPERS_H_

#include <utility>

#include "berberis/guest_abi/guest_abi.h"  // IWYU pragma: export.
#include "berberis/guest_abi/guest_function_wrapper.h"
#include "berberis/guest_abi/guest_params.h"
#include "berberis/guest_abi/guest_type.h"
#include "berberis/runtime_primitives/host_code.h"
#include "berberis/runtime_primitives/host_function_wrapper_impl.h"

namespace berberis {

// Setup and run trampoline function.
template <typename Func,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
class TrampolineFuncGenerator;

template <typename Res,
          typename... Args,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
class TrampolineFuncGenerator<Res(Args...), kCallingConventionsVariant> {
 public:
  static void Func(HostCode callee, ThreadState* state) {
    using Func = Res (*)(Args...);
    auto func = reinterpret_cast<Func>(const_cast<void*>(callee));
    FuncImpl(func, state, std::make_index_sequence<sizeof...(Args)>());
  }

 private:
  template <typename Func, typename std::size_t... I>
  static void FuncImpl(Func func, ThreadState* state, std::index_sequence<I...>) {
    GuestParamsValues<Func, kCallingConventionsVariant> params(state);
    if constexpr (std::is_same_v<Res, void>) {
      func(GetArgument<I>(params)...);
    } else if constexpr (std::is_pointer_v<Res> && std::is_function_v<std::remove_pointer_t<Res>>) {
      auto&& [ret] = GuestReturnReference<Func, kCallingConventionsVariant>(state);
      ret = WrapResultFunction(func(GetArgument<I>(params)...));
    } else {
      auto&& [ret] = GuestReturnReference<Func, kCallingConventionsVariant>(state);
      ret = func(GetArgument<I>(params)...);
    }
  }

  template <std::size_t index, typename GuestParams>
  static auto GetArgument(const GuestParams& params) {
    using Arg = std::tuple_element_t<index, std::tuple<Args...>>;
    if constexpr (std::is_pointer_v<Arg> && std::is_function_v<std::remove_pointer_t<Arg>>) {
      return WrapGuestFunction(params.template get<index>(), "AutoGeneratedWrapper");
    } else {
      return params.template get<index>();
    }
  }

  template <typename ResultRes, typename... ResultArgs>
  static GuestType<ResultRes (*)(ResultArgs...)> WrapResultFunction(
      ResultRes (*func)(ResultArgs...)) {
    WrapHostFunctionImpl(
        reinterpret_cast<HostCode>(func),
        TrampolineFuncGenerator<ResultRes(ResultArgs...), kCallingConventionsVariant>::Func,
        "AutoGeneratedWrapper");
    return func;
  }
};

// Pointer to function.
template <typename Res,
          typename... Args,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
class TrampolineFuncGenerator<Res (*)(Args...), kCallingConventionsVariant>
    : public TrampolineFuncGenerator<Res(Args...), kCallingConventionsVariant> {};

// Syntax sugar.
template <typename Func,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
constexpr TrampolineFunc GetTrampolineFunc() {
  return TrampolineFuncGenerator<Func, kCallingConventionsVariant>::Func;
}

template <GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi,
          typename Func>
inline void WrapHostFunction(Func func, const char* name) {
  WrapHostFunctionImpl(reinterpret_cast<HostCode>(func),
                       GetTrampolineFunc<Func, kCallingConventionsVariant>(),
                       name);
}

}  // namespace berberis

#endif  // BERBERIS_GUEST_ABI_FUNCTION_WRAPPERS_H_
